[tools]
babashka = "1.12.209"
clojure = "1.12.0.1495"
java = "17"
maven = "3.9.11"

[tasks.test]
run = """clojure -X:test"""

[tasks.fmt]
run = "clj -Ttools install io.github.weavejester/cljfmt '{:git/tag \"0.15.3\"}' :as cljfmt && clj -Tcljfmt fix"

[tasks.pom]
run = "clojure -T:build pom"

[tasks.jar]
run = "clojure -T:build jar"

[tasks.install]
run = "clojure -X:deps mvn-install"

[tasks.deploy]
run = "clojure -T:build deploy"

[tasks.clean]
run = "rm -rf target"
